### PR TITLE
Add .nvmrc - Node v 16.8.0

### PR DESCRIPTION
**Pull request by cstavitsky**
- Add `.nvmrc` to lock in node version

### CODE REVIEW

**Comment by cstavitsky** [comment]
Closing real quick until I can verify this...

**Comment by cstavitsky** [comment]
Works, reopening and should be ready to merge

**Review by thinkocapo — APPROVED** [review]
approved. Please merge this.

**Comment by krystofwoldrich** [comment]
- Node upgrade included in https://github.com/sentry-demos/sentry_react_native/pull/35

**Pull request closed without merging**
